### ISSUE TITLE
Update with latest changes from SWC

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-ACI/20170830-git-novice#14]
Hey @pshriwise 
I was thinking it would be nice to update our version of the lessons [to the lastest swc ones](https://github.com/swcarpentry/git-novice).  I went through some which I could easily diff and most of the changes were small but nice improvements.
I'm thinking maybe this could be done with a rebase but as I've never done one before I could use some advice.  What do you think? 
Sarah

**Comment by pshriwise** [comment]
Yeah I think that would be right move in terms of keeping a clean history, but it's a little tricky because this would require a force push at some point to rewrite the history the `gh-pages` branch (I think). I still think its the way to go so that future updates to those lessons can be incorporated here though if you're comfortable with it.

To make future updates easier, I think I'd recommend making a `gh-pages-upstream` branch in this repo that is always in sync with the latest swc lessons. The served `gh-pages` branch here will always be based on that.

So the steps would be:

  - add the newest lessons repo as a remote and fetch the branches
  - checkout the newest lessons repo `gh-pages` branch under a new name (`gh-pages-upstream` or something like that)
  - push `gh-pages-upstream` to this reapo
  - rebase the `gh-pages` branch of this repo onto `gh-pages-upstream` and handle any conflicts
  - Then this (I think) will require a force push to update the branch history to this repo

and then it should be all set! Fingers crossed for no conflicts...

**Comment by sstevens2** [comment]
Maybe you can walk me through this tomorrow at the meeting?

**Comment by pshriwise** [comment]
Sure thing!
